### ISSUE TITLE
Nije moguće kreirati Izvještaj o podacima klubova

### ISSUE THREAD

**Issue by tarikdemirovic** [SoftverInzenjeringETFSA/SI2014Tim9#36]
Komponenta:
Izvještaji

Commit ID:
6b368996cda563c8055639f827578247953a5ca2

Opis problema:
Ukoliko se klikne na tabu Izvještaji na dugme Izvještaj o podacima klubova, aplikacija krahira, zbog grešaka koje se javljaju pri importovanju projekta (LocalDateTime cannot be resolved...)

Koraci za reproduciranje:
1. Pokrenuti aplikaciju
2. Unijeti korisničke podatke
3. Preći na tab "Izvještaji"
4. Kliknuti na "Izvještaj o podacima klubova"

Dobijeni rezultat:
- Aplikacija zamrzne, u eclipse-u se pojavljuje exception.
- Stack trace:
  Exception in thread "AWT-EventQueue-0" java.lang.Error: Unresolved compilation problem: 
  The import java.time cannot be resolved
  
  at gui.IzvjestajOPodacimaKlubova.<init>(IzvjestajOPodacimaKlubova.java:33)
  at gui.GlavniProzor$16.actionPerformed(GlavniProzor.java:711)
  at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
  at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
  at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
  at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
  at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
  at java.awt.Component.processMouseEvent(Component.java:6516)
  at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
  at java.awt.Component.processEvent(Component.java:6281)
  at java.awt.Container.processEvent(Container.java:2229)
  at java.awt.Component.dispatchEventImpl(Component.java:4872)
  at java.awt.Container.dispatchEventImpl(Container.java:2287)
  at java.awt.Component.dispatchEvent(Component.java:4698)
  at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
  at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
  at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
  at java.awt.Container.dispatchEventImpl(Container.java:2273)
  at java.awt.Window.dispatchEventImpl(Window.java:2719)
  at java.awt.Component.dispatchEvent(Component.java:4698)
  at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
  at java.awt.EventQueue.access$300(EventQueue.java:103)
  at java.awt.EventQueue$3.run(EventQueue.java:706)
  at java.awt.EventQueue$3.run(EventQueue.java:704)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
  at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
  at java.awt.EventQueue$4.run(EventQueue.java:720)
  at java.awt.EventQueue$4.run(EventQueue.java:718)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
  at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
  at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

Očekivani rezultat:
- Prikazivanje forme sa izvještajem

**Comment by tarikdemirovic** [comment]
Iz istog razloga ne mogu ni jedan izvještaj generisati.

**Comment by kiselitza** [comment]
Obzirom da niko iz razvojnog tima nema ovaj problem, razlog je vjerovatno sadržan u korištenju različitog Java SE Development Kit-a
