### ISSUE TITLE
Edit takmičara iz tabele

### ISSUE THREAD

**Issue by tarikdemirovic** [SoftverInzenjeringETFSA/SI2014Tim9#39]
Komponenta:
Forma za editovanje korisničkih podataka

Commit ID:
6b36899

Opis problema:
NullPointerException pri odabiru opcije za editovanje takmičara iz tabele takmičara.

Koraci za reproduciranje:
1. Pokrenuti aplikaciju
2. Unijeti login podatke
3. Odabrati tab "Takmičari"
4. Odabir opcije za editovanje iz tabele za nekog od takmičara

Dobijeni rezultat:
- NullPointerException
- Stack trace:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at gui.DodavanjeTakmicara.<init>(DodavanjeTakmicara.java:653)
    at gui.GlavniProzor$12.mouseClicked(GlavniProzor.java:582)
    at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
    at java.awt.Component.processMouseEvent(Component.java:6519)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
    at java.awt.Component.processEvent(Component.java:6281)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4872)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4501)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4698)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:720)
    at java.awt.EventQueue$4.run(EventQueue.java:718)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

Očekivani rezultat:
- Forma za editovanje podataka o takmičaru

**Comment by kiselitza** [comment]
b3d63bee4569738a06eb64f5b4d71fdd7ea55a8d popravljeno
